### ISSUE TITLE
Call for volunteers for HydPy

### ISSUE THREAD

**Issue by chirag200666** [HydPy/HydPy#13]
Call for volunteers page for HydPy community needs to be put up, should have roles/responsibilities etc. and should link to a google form.

**Comment by ananyo2012** [comment]
@chirag200666 Do we still need this ?

**Comment by ananyo2012** [comment]
We should add a line saying volunteers are welcome and connect with us through our regular meetups.

**Comment by ananyo2012** [comment]
Need to decide a place where we can add this.

**Comment by chirag200666** [comment]
In the about us page, we have a google form for volunteers & few people filled it in the last few months, so I think we can close the issue.
