### ISSUE TITLE
Call for speakers for regular HydPy sessions

### ISSUE THREAD

**Issue by chirag200666** [HydPy/HydPy#14]
We need a form where people interested in giving sessions can fill in their contact details and topics they are interested to speak on.

**Comment by ananyo2012** [comment]
We can use the same form available at http://www.hydpy.org/pyexpresshyd/ . But we do need a separate page which is more visible to speakers.

**Comment by ananyo2012** [comment]
We need to have something more open where people can easily submit their talks and it is viewable by other people as well. I recommend using a separate repo for talks where people can submit their talks as GitHub Issues. How does this sound @chirag200666 ? PyDelhi uses this for their meetups as well https://pydelhi.org/ . We can use a custom Issue template where people can add their talk details.

**Comment by chirag200666** [comment]
Solved using https://github.com/HydPy/HydPy/pull/34
