### ISSUE TITLE
PythonMonth Hyderabad 2017 with PythonExpress announcement on HydPy website

### ISSUE THREAD

**Issue by chirag200666** [HydPy/HydPy#16]
The pythonexpress session announcement on HydPy website is required.
We are collaborating with PSSI to reach as many colleges as possible in Hyderabad for the Python Month.

http://blog.pythonexpress.in/posts/python-month-2017/

**Comment by chirag200666** [comment]
Details of the campus ambassador program need to be added and the college Ambassador form.

**Comment by ananyo2012** [comment]
Done in http://www.hydpy.org/pyexpresshyd/ . Closing this issue.
