### ISSUE TITLE
Update Dates for Conference

### ISSUE THREAD

**Issue by nithinmulley** [HydPy/HydPy#17]
http://www.hydpy.org/pyconf/conference/python/pyconf-hyderabad-2017

Though Image has correct dates, Title has only Oct-7 and the Maps show Oct-8. A little more clarity about both dates is required. People can figure out, but this is still an error.

![image](https://user-images.githubusercontent.com/31166151/29753044-2c62a822-8b37-11e7-8e26-5670e1fbf94a.png)

**Comment by ananyo2012** [comment]
Filed #26 to address issues of this kind.
