### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by ananyo2012** [HydPy/HydPy#31]
We should have a CoC page in our website which participant need to adhere during the meetups. @manitha Can you provide the CoC content that we can put in the website ?

**Comment by chirag200666** [comment]
let's start from the one at PyCon India.

**Comment by chirag200666** [comment]
added in PR: https://github.com/HydPy/HydPy/pull/38

**Comment by chirag200666** [comment]
@ananyo2012 
The one in PyCon India has been adopted from PSF's COC for PyCon US, that works for hydPy as well.

**Comment by ananyo2012** [comment]
@chirag200666 Well it works well for now. But it is more specific to Conferences. Can we have a appropriate version that applies to general communication and meetups ? Like the line `Code for Exhibitors and Sponsors` won't be required.
