### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by chirag200666** [HydPy/HydPy#39]
A drop-down menu will be good to club things together.

**Comment by felipeemarcon** [comment]
This issue still open yet? You need some help?

**Comment by ananyo2012** [comment]
@felipeemarcon There is a more larger issue #42 that deals with the theme update. We would like to discuss this as a part of that update. If you have inputs please do let us know in comments.

**Comment by RajatRajdeep** [comment]
The website has been revamped, Closed this issue as the dropdown menu is not required now.
