### ISSUE TITLE
Change the website theme, its quite old now

### ISSUE THREAD

**Issue by inovizz** [HydPy/HydPy#42]
In general, I'm looking the at the website theme to be changed now. So that website look and feel is improved. Secondly, when we are working on this issue, let's make sure that we make content configurable. If possible - having something like Django-Admin would help us add new events and details about the meetup without even doing a deployment or code push.

If the idea is not clear then please feel free to post questions here, I'll be happy to answer.

**Comment by bhansa** [comment]
I remember @GoelJatin was working on an interface using django, where people can post the proposals for talks and the speaker selection can also be done.
It will be really helpful to schedule events, confirm speakers and venue if we put that interface online. 

@GoelJatin please add your suggestions :)

**Comment by inovizz** [comment]
Ok, I'll build on top of this w.r.t backend but Bharat and Ananyo I'd need help with theme and frontend upgrade.

**Comment by bhansa** [comment]
Yeah, we'll update the UI for both website and the web interface _(we need to give it some name though :p)_.

@subuhani will you be able to help here to design new mockup for the website.
It is a small website, so we will be able to use the refactor the components and change the UI.

**Comment by RajatRajdeep** [comment]
I'll start working on this. Please assign it to me.

**Comment by RajatRajdeep** [comment]
Could you please confirm whether the following pages are currently in use? I noticed that they are not being redirected from our website. If these pages are no longer needed, we can move them to deprecated status to save time on revamping and to streamline the code structure:
1. https://www.hydpy.org/events/
2. https://www.hydpy.org/pyexpresshyd/
3. https://www.hydpy.org/category/
4. https://www.hydpy.org/activities/

**Comment by RajatRajdeep** [comment]
The changes have been made.
Ref PR: https://github.com/HydPy/HydPy/pull/56
