### ISSUE TITLE
Record meetup session

### ISSUE THREAD

**Issue by ram-sagar-mourya** [HydPy/HydPy#9]
We need to record our meetup sessions and post the videos online.

**Comment by chirag200666** [comment]
@ram-sagar-mourya 
can you please put up an action plan of how can we achieve this. 
Thanks

**Comment by ananyo2012** [comment]
@chirag200666 The PyLadies event maybe a good time to start recording the sessions. Need to discuss further possibilties

**Comment by ananyo2012** [comment]
I think this still remains a logistical problem and also the main moto of meeting and connecting with people in meetups is not served. So I think it's not a good idea to record sessions in meetups. We can take this discussion offline if needed. Closing this issue for now.
